### ISSUE TITLE
nvchad_ui.icons module not found

### ISSUE THREAD

**Issue by inifares23lab** [NvChad/NvChad#1362]
**Describe the bug**
the module nvchad_ui.icons is not found and an error is displayed when opening neovim

**To Reproduce**
1. Open neovim
2. problem loading nvchad_ui.icons 

**Expected behavior**
No Error

**Screenshots**
![image](https://user-images.githubusercontent.com/62902848/180598517-b39110ce-629e-4aea-aea8-efb9e2dca976.png)

**Desktop (please complete the following information):**
 - Operating System : fedora 36
 - Terminal : alacritty, gnome-console, gnome-terminal
 - Version of Neovim : NVIM v0.7.2

**Additional context**
1. Not sure why is not finding the module but maybe the error could be fixed like this:
file: ~/.config/nvim/lua/plugins/configs/others.lua 
![image](https://user-images.githubusercontent.com/62902848/180599000-16340e42-54d7-4528-b2a8-02300bfbdf23.png)

2. also the icons seems to be working anyway in alpha dashboard, telescope, nvim_tree

**Comment by siduck** [comment]
how do you reproduce this?

**Comment by tomasky** [comment]
Obviously not the latest version

**Comment by inifares23lab** [comment]
hi
I updated with <leader>uu some days ago
since then it started displaying the error whenever starting neovim

**Comment by tomasky** [comment]
try to reinstall nvchad

**Comment by siduck** [comment]
@inifares23lab this is an old issue, always do packersync straight after leader uu ( even tho this should be automatic but sometimes the user interrupts)

**Comment by tomasky** [comment]
no ,Even if there is no interruption, `:PackerSync` must be done

**Comment by siduck** [comment]
btw is github comments broken for u too? @tomasky 

![image](https://user-images.githubusercontent.com/59060246/180629252-6affdc22-77d8-44c2-adac-70252aad0c10.png)


you commented just now but github shows it 6 hours ago

**Comment by tomasky** [comment]
ye, it is from time to time

**Comment by yingzhu146** [comment]
I have the exact same issue - should probably be reopened

OSX, M1 , NVIM v0.8.0-dev+1878-g7f8f8d6cb
Darwin MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000 arm64

I'm on NvChad master, on commit `817aeea`.

Yes I did run PackerSync.

**Comment by siduck** [comment]
please do a clean install and make a video of it :/

**Comment by yingzhu146** [comment]
thanks a lot for the fast reply!

This comes from a clean install (as said, I have confirmed that I'm running the most recent commit) - I've deleted all the caches etc.

I can't do a video but it also doesn't do much more than show the exact same error as OP above - I've copied it below here

```
packer.nvim: Error running config for nvim-web-devicons: /Users/yingzhu/.config/nvim/lua/plugins/configs/others.lua:166: module 'nvchad_ui.icons' not found:
^Ino field package.preload['nvchad_ui.icons']
^Ino file '/opt/homebrew/Cellar/luarocks/3.5.0/share/lua/5.1/nvchad_ui/icons.lua'
^Ino file '/opt/homebrew/share/lua/5.1/nvchad_ui/icons.lua'
^Ino file '/opt/homebrew/share/lua/5.1/nvchad_ui/icons/init.lua'
^Ino file '/opt/homebrew/lib/lua/5.1/nvchad_ui/icons.lua'
^Ino file '/opt/homebrew/lib/lua/5.1/nvchad_ui/icons/init.lua'
^Ino file './nvchad_ui/icons.lua'
^Ino file './nvchad_ui/icons/init.lua'
^Ino file '/Users/yingzhu/.luarocks/share/lua/5.1/nvchad_ui/icons.lua'
^Ino file '/Users/yingzhu/.luarocks/share/lua/5.1/nvchad_ui/icons/init.lua'
^Ino file '/Users/yingzhu/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/nvchad_ui/icons.lua'
^Ino file '/Users/yingzhu/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/nvchad_ui/icons/init.lua'
^Ino file '/Users/yingzhu/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/nvchad_ui/icons.lua'
^Ino file '/Users/yingzhu/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/nvchad_ui/icons/init.lua'
^Ino file '/Users/yingzhu/.luarocks/lib/lua/5.1/nvchad_ui/icons.so'
^Ino file '/Users/yingzhu/.luarocks/lib/lua/5.1/nvchad_ui/icons.dylib'
^Ino file '/Users/yingzhu/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/nvchad_ui/icons.so'
^Ino file '/Users/yingzhu/.luarocks/lib/lua/5.1/nvchad_ui.so'
^Ino file '/Users/yingzhu/.luarocks/lib/lua/5.1/nvchad_ui.dylib'
^Ino file '/Users/yingzhu/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/nvchad_ui.so'

```

This looks like some config/loading issue but my config was working.

Additionally, I can without problem manually load the thing via `:lua print(vim.inspect(require('nvchad_ui.icons')))' I'm getting a healthy looking table back

```
  devicons = {
    Dockerfile = {
      icon = "",
      name = "Dockerfile"
    },
...
```

**Comment by yingzhu146** [comment]
also probably obvious but after removing the problematic line

```
"lua/plugins/configs/others.lua" line 166 of 173 --95%-- col 9
```
everything works

**Comment by tomasky** [comment]
try to :PackerSync

**Comment by tomasky** [comment]
try to :PackerSync again

**Comment by siduck** [comment]
yea people forget to do it :/

**Comment by tomasky** [comment]
I still don't understand, why do I need to   PackerSync sometimes after updating nvchad

**Comment by tomasky** [comment]
Even though I chose to update all the  plugins when I updated NvChad

**Comment by siduck** [comment]
> Even though I chose to update all the plugins when I updated NvChad

yea cuz nvim config isnt hot reloaded so doing packersync straight after git pull is useless imo 



@LeonHeidelbach

**Comment by tomasky** [comment]
try this, No deep testing


```lua
--nvchad/updater/update.lua
 if packer_sync then
            vim.cmd [[luafile $MYVIMRC]]
            vim.cmd [[PackerSync]]
         end

```

**Comment by siduck** [comment]
> try this, No deep testing
> 
> ```lua
> --nvchad/updater/update.lua
>  if packer_sync then
>         vim.cmd [[luafile $MYVIMRC]]
>         vim.cmd [[PackerSync]]
>  end
> ```

this reloads whole config? :thinking:

**Comment by tomasky** [comment]
i reset nvchad and ui plugin, then <space+uu> ,then open nvim ,no errors report

**Comment by tomasky** [comment]
@siduck  try it , it should be   helpful

**Comment by siduck** [comment]
> @siduck try it , it should be helpful

I will try it once there are updates in this repo

**Comment by yingzhu146** [comment]
without specifying what I should look for in PackerStatus it's hard to see what you're trying to get at here @tomasky with your suggestion , but it shows NvChad/ui is properly installed if that's what you're looking for. I also explained/provided evidence that I can load the package manually.

**Comment by siduck** [comment]
> Why was this closed? @tomasky as I mentioned in my post, I did PackerSync and it didn't help.

because its just you facing this issue and this was fixed in the recent commits. Do a clean install and check again

**Comment by tomasky** [comment]
@yingzhu146  
```shell
cd ~/.local/share/nvim/site/pack/packer 
rm -r opt
nvim
```
exec:   `:PackerSync`

**Comment by tomasky** [comment]
@siduck  maybe because sometimes `git reset --hard` ,some plugins dir are dirty

**Comment by siduck** [comment]
> @siduck maybe because sometimes `git reset --hard` ,some plugins dir are dirty

i think so , i did that 1-2 times recently

**Comment by yingzhu146** [comment]
@tomasky @siduck that's exactly what I did when I said this comes from a clean install and that I deleted the cache and that I ensured I'm on master's last commit, then `ln -s ~/my_old_custom_config ~/.config/nvim/lua/custom` and PackerSync'ed.

**Comment by siduck** [comment]
does it work without your custom config?

**Comment by yingzhu146** [comment]
Yes - which is why I thought this was some config/loading issue. Since I have nothing in my config that touches nvim_ui I don't know what the issue might be - the config is a bit large for binary dissect - all of my config code still works, and if I comment out that one line above everything works as intended. Additionally, as said, after loading I can run that line without issue so it sounds like a lazy loading issue to me?

**Comment by 0x736d** [comment]
I was having the same exact issue after updating when ui related modules got moved to `NvChad/ui`. It seems using plugins that depend on `nvim-web-devicons` were causing this error on startup even if `nvchad_ui.icons` is not used anywhere is custom config.

In my case it was `nvim-spectre`, for some reason loading `nvim-spectre` after `plenary.nvim` made the error go away on startup.

There were some other instances where I got the exact same error, but doing a clean install fixed it for me.

**Comment by yingzhu146** [comment]
that's super helpful, thanks @0x736d - I do use `nvim-web-devicons` in other places, I'll have a look at that!

**Comment by tomasky** [comment]
maybe because this, nvim-web-devicons may  loads before ui plugin


```lua
["kyazdani42/nvim-web-devicons"] = {
    module = "nvim-web-devicons",
    config = function()
      require("plugins.configs.others").devicons()
    end,
  },
```

**Comment by siduck** [comment]
@yingzhu146 does this fix it?

```lua
  ["NvChad/ui"] = {
    after = "base46",
    module = "nvchad_ui",
    config = function()
      require("plugins.configs.others").nvchad_ui()
    end,
  },
  ```
  
  add this in the default plugin list and test

**Comment by br1anchen** [comment]
> @yingzhu146 does this fix it?
> 
> ```lua
>   ["NvChad/ui"] = {
>     after = "base46",
>     module = "nvchad_ui",
>     config = function()
>       require("plugins.configs.others").nvchad_ui()
>     end,
>   },
> ```
> 
> add this in the default plugin list and test

I had same issue before, I used to do `PackerCompile` after `PackerSync` from time to time to resolve this issue, it seems like race condition caused by multiple plugins depends on `nvim-web-devicons`.

**Comment by yingzhu146** [comment]
> @yingzhu146 does this fix it?
> 
> ```lua
>   ["NvChad/ui"] = {
>     after = "base46",
>     module = "nvchad_ui",
>     config = function()
>       require("plugins.configs.others").nvchad_ui()
>     end,
>   },
> ```
> 
> add this in the default plugin list and test

This + PackerCompile fixes it - thanks a ton!

**Comment by siduck** [comment]
> > @yingzhu146 does this fix it?
> > ```lua
> >   ["NvChad/ui"] = {
> >     after = "base46",
> >     module = "nvchad_ui",
> >     config = function()
> >       require("plugins.configs.others").nvchad_ui()
> >     end,
> >   },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > add this in the default plugin list and test
> 
> This + PackerCompile fixes it - thanks a ton!

hm, good. I'll make this change to the repo. Thx for confirming :)

**Comment by tomasky** [comment]
@siduck  my pr has fixed this

**Comment by siduck** [comment]
> @siduck my pr has fixed this

yep seen, was sick before and still sick so didnt had the time to test it. Btw why bufenter? It would also mean that lspconfig will load into a buffer regardless of that buffer being a file or not

**Comment by tomasky** [comment]
i have tested it, it works,

**Comment by tomasky** [comment]
Do you have a cold? You should get plenty of hot water

**Comment by siduck** [comment]
> Do you have a cold? You should get plenty of hot water

yes and running nose, its very irritating. I have to keep a cloth with me and keep wiping my nose with my left hand and type with my right hand :disappointed:

**Comment by tomasky** [comment]
You should be able to drink some traditional  chinese medicine. It is helpful

**Comment by tomasky** [comment]
You should be able to drink some traditional  chinese medicine. It is helpful

**Comment by siduck** [comment]
> You should be able to drink some traditional chinese medicine. It is helpful

i dont have such ingredients here so i have to heal on my own

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/pull/1396

**Comment by carlisia** [comment]
Hey folks 👋

This problem occurs for me on a fresh install. See the screen recording: https://share.cleanshot.com/2Q2R71 

Steps I took:
- Modified my `chadrc` to include:
```
  ["NvChad/ui"] = {
    after = "base46",
    module = "nvchad_ui",
    config = function()
      require("plugins.configs.others").nvchad_ui()
    end,
  },
```
- reinstalled nvchad:
```
rm -rf ~/.cache/nvim
rm -rf ~/.local/share/nvim
rm -rf ~/.config/nvim/
git clone https://github.com/NvChad/NvChad.git ~/.config/nvim
+ symlinked to my custom dir (using stow)
nvim
```


The error shows up after the plugins are loaded.

**Comment by siduck** [comment]
@carlisia dont modify the nvchad/ui plugin

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/182911932-326df9a5-74fc-444a-95fa-9d9eb86ae4df.png)

that was fixed already, webdevicons plugin is loaded after the ui plugin now

**Comment by siduck** [comment]
also i doubt if u need a code runner https://github.com/carlisia/dotfiles/blob/main/nvim/.config/nvim/lua/custom/plugins/init.lua#L390 

our nvterm plugin does a similar thing.  check https://github.com/NvChad/nvterm#additional-functionality

**Comment by carlisia** [comment]
Hm. Then it's weird. I removed that bit and it still happens 😅

I'll send another screen shot and the content of my `chadrc`, 1 sec.

**Comment by siduck** [comment]
> Hm. Then it's weird. I removed that bit and it still happens sweat_smile
> 
> I'll send another screen shot and the content of my `chadrc`, 1 sec.

happens with vanilla nvchad btw?

**Comment by carlisia** [comment]
> > Hm. Then it's weird. I removed that bit and it still happens sweat_smile
> > I'll send another screen shot and the content of my `chadrc`, 1 sec.
> 
> happens with vanilla nvchad btw?

No, I don't think so. Will test to confirm.

I know I have added plugins that require the `nvim-web-devicons`. Should I go thru which ones they are and add `after = nvim-web-devicons`?

**Comment by siduck** [comment]
yes do that

**Comment by carlisia** [comment]
To answer your previous question: it does not happen with vanilla and am getting the error below. I see by running packer.status that it is on the list, and it's not unloaded.

![CleanShot 2022-08-04 at 10 39 19](https://user-images.githubusercontent.com/16508/182915523-c33ef880-d394-4700-99ec-65d4aadbee81.png)

**Comment by siduck** [comment]
> To answer your previous question: it does not happen with vanilla nvchad.
> 
> I reversed my `chadrc` and added the `after`, am getting the error below. I see by running packer.status that it (`nvim-web-devicons`) is on the list, and it's not unloaded.
> 
> ![CleanShot 2022-08-04 at 10 39 19](https://user-images.githubusercontent.com/16508/182915523-c33ef880-d394-4700-99ec-65d4aadbee81.png)

very weird, its just for octo.nvim?

**Comment by siduck** [comment]
you can join one of our groups, click on the readme badges 
![image](https://user-images.githubusercontent.com/59060246/182976125-21bf4843-5455-4f3d-a31b-f91a5c9628c3.png)

many might be able to help you there when Im offline

**Comment by carlisia** [comment]
I got to the bottom of this! 😆
And fixed it, actually with help from this discussion (see below). Def not a NvChad issue. Thanks for the help! This can be closed again as far as I'm concerned.

---

I had made the quick and lazy assumption that any plugin that required `nvim-web-devicons` would cause that error. Today I had more time and turned off every plugin except Octo, which didn't cause the error. 🤔

## How I solved it
Turned off all plugins. Turned plugins back on blocks at a time til I narrowed to the only one causing that error message. I solved it by taking a hint from https://github.com/NvChad/NvChad/issues/1362#issuecomment-1205902943 and lazy loading it with a `cmd`. Using the `packer_lazy_load` function (see the bottom of this message for more about this function) that I use to lazy load other plugins did not work for this case.  Below is the culprit, now fully working w/o errors:

```
  ["stevearc/aerial.nvim"] = {
    cmd = "AerialToggle",
    config = function()
      require("custom.plugins.common").aerial()
    end,
  },
```

## How to configure Octo
In case someone lands here looking for how to configure Octo, it took me a while to nail it. Below is what my fully working config looks like. Besides that, I also had to ad "octo" to the list of Telescope extensions.

```
  ["pwntester/octo.nvim"] = {
    after = "telescope.nvim",
    requires = {
      "kyazdani42/nvim-web-devicons",
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim",
    },
    config = function()
      require("octo").setup()
    end,
    setup = function()
      require("custom.utils").packer_lazy_load("telescope.nvim", 500)
    end,
  },
```

PS: My setup is basically using all of @Akianonymus configs, and that `packer_lazy_load` is a copy of this:

https://github.com/Akianonymus/dotfiles/blob/276a54629571892f6689d4a47b2395ab8bbcf664/src/.config/nvim/lua/custom/utils.lua#L32-L36.

**Comment by siduck** [comment]
@carlisia i doubt if you need that requires , after, setup section. You can make telescope lazyload at its module too 

```lua
["nvim-telescope/telescope.nvim"] = {
    module = "telescope",
  },
```

So if any plugin that needs telescope calls any telescope stuff then telescope plugin will automatically load

**Comment by Akianonymus** [comment]
@carlisia Hah, that's what you get for using my mess, haha.

Anyway i use the packer_lazy_load function along with the module lazy load, so that all the telescope commands are available later, i usually load it after 1 second, so it doesn't harm my startup time or block my editor ui.

But it can create a mess if not used properly.

**Comment by carlisia** [comment]
Lots of learnings! Thanks for sharing these options and explanationsI will give these suggestions a try.

I currently have 70 plugins at the moment and everything is working w/o a hitch now!

**Comment by p5a0u9l** [comment]
@siduck , great work with this config. Wanted to note that I saw this issue as well. Struggled with re-installing nvchad from scratch, updating, different Packer stuff, finally one-by-one disabling all plugins until I zero'd in on aerial. frustrating

So, is the consensus that the aerial plugin is "at fault" here. did anyone create an issue for that repo?

**Comment by siduck** [comment]
> @siduck , great work with this config. Wanted to note that I saw this issue as well. Struggled with re-installing nvchad from scratch, updating, different Packer stuff, finally one-by-one disabling all plugins until I zero'd in on aerial. frustrating
> 
> So, is the consensus that the aerial plugin is "at fault" here. did anyone create an issue for that repo?

load aerial after nvim-webdevicons plugin
