### ISSUE TITLE
Cheatsheet doesn't open; Err: plenary.nvim not installed

### ISSUE THREAD

**Issue by hamxabaig** [NvChad/NvChad#307]
**Describe the bug**
Cheatsheet command is not working, it throws an error:
```
Error detected while processing function <SNR>50_Cheatsheet:
line    5:
E5108: Error executing lua .../pack/packer/opt/cheatsheet.nvim/lua/cheatsheet/init.lua:82: plenary.nvim not installed
Press ENTER or type command to continue
```

I followed the steps from installation page and everything else seems to be working fine. PackerSync/Install also works without issue.

**To Reproduce**
1. Open nvim
2. Type :Cheatsheet
3. See error

**Expected behavior**
It should open cheatsheet

**Screenshots**
<img width="1440" alt="Screen Shot 2021-08-20 at 11 18 31 AM" src="https://user-images.githubusercontent.com/12872177/130188863-94b74ea9-f109-41be-a66b-55f071e7f081.png">

**Desktop (please complete the following information):**
 - M1 Mac - BigSur
 - iTerm2 3.4
 - NVIM v0.5.0

**Comment by G-Rowell** [comment]
Hi @hamxabaig,

Can you try run `:PackerSync`
then restart NeoVim,
then run `:Cheatsheet` 

for me to check?

Thanks

**Comment by Akianonymus** [comment]
Can confirm the issue

**Comment by siduck76** [comment]
this was with the old config , try cheatsheet on new config . works for me

**Comment by hamxabaig** [comment]
Thanks for prompt reply @G-Rowell, I just ran PackerSync and restarted nvim, still the same.

**Comment by siduck76** [comment]
> Thanks for prompt reply @G-Rowell, I just ran PackerSync and restarted nvim, still the same.

update your nvchad config!

**Comment by hamxabaig** [comment]
@siduck76 how can i do that?

**Comment by Akianonymus** [comment]
> Thanks for prompt reply @G-Rowell, I just ran PackerSync and restarted nvim, still the same.

Same happened here

just remove ~/.config/nvim/plugin folder then PackerCompile

restart neovim and it should work

**Comment by hamxabaig** [comment]
@Akianonymus @siduck76 

Updated the config, restarted still the same issue.

Removed plugins folder, recompiled and restarted. Doesn't work

**Comment by siduck76** [comment]
show me your cheatsheet.nvim section in pluginlist.lua

**Comment by hamxabaig** [comment]
@siduck76 this one?

![Uploading Screen Shot 2021-08-20 at 11.49.53 AM.png…]()

**Comment by siduck76** [comment]
> @siduck76 this one?
> 
> <img alt="image" width="649" src="https://user-images.githubusercontent.com/12872177/130192402-c04975f0-b91f-499e-b762-037d27d8b51e.png">

looks fine :l

**Comment by hamxabaig** [comment]
@siduck76 Do you think its something related to `plenary.nvim` not being installed or smth? How can i check if its installed or not?

```
E5108: Error executing lua .../pack/packer/opt/cheatsheet.nvim/lua/cheatsheet/init.lua:82: plenary.nvim not installed
Press ENTER or type command to continue
```

**Comment by G-Rowell** [comment]
Can you double check that this line is set to true **locally**
https://github.com/NvChad/NvChad/blob/main/lua/chadrc.lua#L76

Then run `:PackerStatus`
and check if `plenary.nvim` is listed, it should ideally **not** have `(not loaded)` beside it

Hmmmm,
I'm sure we can sort this out, sorry for all the mess :thinking:

**Comment by hamxabaig** [comment]
@G-Rowell no worries, thank you for your efforts on this.

I think that plugin is not installed, I just skimmed through the list and there is none with that name.

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/12872177/130194288-3be5bc84-ea39-428e-8ee3-1b81fc5f7eb7.png">

Also cheatsheet is set to true.

**Comment by G-Rowell** [comment]
Hahah, I was just bout to say it's right there, and loaded!

Hmmmmmm, this is very very strange......

Sorry to be super pedantic, can you check `:PackerStatus` to **ensure plenary.nvim is loaded` then run  `:Cheatsheet`?

**Comment by hamxabaig** [comment]
🤔 Weird, its loaded i think.

<img width="1149" alt="Screen Shot 2021-08-20 at 12 14 28 PM" src="https://user-images.githubusercontent.com/12872177/130194956-1eb5164b-7ed0-4902-9c7b-11e148fd4777.png">

**Comment by G-Rowell** [comment]
Huh, super duper strange

I'm happy to debug this more at some point, I do have a commitment I have to go to rn though

**Comment by siduck76** [comment]
@hamxabaig you sure that you have updated the config?

**Comment by hamxabaig** [comment]
@siduck76 yeah i ran Space + uu and it did fetch from git repo. Happy to do it again. Let me try.

@G-Rowell No worries, not a big issue rn. I mainly use VSCode + Vim. Best of both worlds. But this looked exciting so thought to myself to try it out.

**Comment by siduck76** [comment]
@hamxabaig back up your nvchad config and do this 

```
git clone https://github.com/NvChad/NvChad ~/.config/nvim
nvim +PackerSync
```

**Comment by hamxabaig** [comment]
@siduck76 tried that but still same error. 😞

**Comment by siduck76** [comment]
> @siduck76 tried that but still same error.


https://user-images.githubusercontent.com/59060246/130205306-733662b3-8a2d-4e16-ba5c-ac35b3789d79.mp4

**Comment by ashincoder** [comment]
@hamxabaig try removing everything. 
Then follow the instructions of https://nvchad.netlify.app/ 
Then mention here what happens

**Comment by TomWright** [comment]
I fixed this issue with:

1. Update Chad: `<leader> + uu`
2. Delete `~/.config/nvim/plugin`
3. `nvim +PackerSync`
4. `:PackerCompile`

I'm not sure which of these steps are strictly necessary but it works now.

**Comment by Eduruiz** [comment]
gotta follow the same steps of @TomWright to get it working, but it's working now.

**Comment by bjesus** [comment]
Can't get it to work... tried the steps @TomWright detailed, and also tried completely removing everything:
```
rm -rf ~/.config/cache/nvim
rm -rf ~/.config/config/nvim
rm -rf ~/.local/share/nvim
```

and I'm still getting exactly the same behavior - PackerStatus shows plenary loaded, but opening the cheatsheet wouldn't work and complain that `plenary.nvim not installed`

**Comment by siduck76** [comment]
> Can't get it to work... tried the steps @TomWright detailed, and also tried completely removing everything:
> 
> ```
> rm -rf ~/.config/cache/nvim
> rm -rf ~/.config/config/nvim
> rm -rf ~/.local/share/nvim
> ```
> 
> and I'm still getting exactly the same behavior - PackerStatus shows plenary loaded, but opening the cheatsheet wouldn't work and complain that `plenary.nvim not installed`

what does nvim -v show?

**Comment by bjesus** [comment]
```
❯ nvim -v
NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.0/build/config -I/build/neovim/src/neovim-0.5.0/src -I/usr/include -I/build/neovim/src/neovim-0.5.0/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.0/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by siduck76** [comment]
this is weird , you sure you're using latest nvchad config (master)? @bjesus

**Comment by bjesus** [comment]
100% sure. `rm -rf ~/.config/nvim ~/.config/.vim ~/.config/.nvim` and git cloned for the 10th time now 🤔

**Comment by siduck76** [comment]
> 100% sure. `rm -rf ~/.config/nvim ~/.config/.vim ~/.config/.nvim` and git cloned for the 10th time now

did u try rm -rf .local/share/nvim ?

**Comment by bjesus** [comment]
Yes. Just did it again, ran `PackerSync` and `PackerCompile`, and all is just the same.

**Comment by siduck76** [comment]
> Yes. Just did it again, ran `PackerSync` and `PackerCompile`, and all is just the same.

its weird that I cant reproduce the error :c 

https://github.com/NvChad/NvChad/issues/307#issuecomment-902531371

**Comment by cocoonkid** [comment]
I have the same Error and tried all suggested steps but no dice.

**Comment by siduck76** [comment]
This issue should persist with older nvchad configs , basically we loaded plenary at bufread event before which was causing this . But with the newest config this must be resolved , check if plenary isn't loaded at bufread and telescope loaded after plenary , then cheatsheet loading after telescope  😆

**Comment by bjesus** [comment]
I'm not sure how new this fix is, but I've only tried installing NvChad for the first time ~12 hours ago. I doubt I ever even had the older NvChad configs...

**Comment by cocoonkid** [comment]
Yes , can confirm. First install here too.

**Comment by siduck76** [comment]
> I'm not sure how new this fix is, but I've only tried installing NvChad for the first time ~12 hours ago. I doubt I ever even had the older NvChad configs...

weird :( . I'll look onto it tonight.

**Comment by siduck76** [comment]
Damn , I get this issue too now : 

![image](https://user-images.githubusercontent.com/59060246/130319047-1dbbdfd9-f230-4081-866d-6b38efaab592.png)

**Comment by siduck76** [comment]
ok fixed it.

**Comment by siduck76** [comment]
@bjesus @cocoonkid check it now! @hamxabaig you too :D

**Comment by bjesus** [comment]
It works!!! thank you so much. Excited to be finally able to start playing with NvChad 🥳

**Comment by siduck76** [comment]
> It works!!! thank you so much. Excited to be finally able to start playing with NvChad

really sorry I forgot to remove the vimenter event before! Glad it works :D

**Comment by hamxabaig** [comment]
Works like a charm @siduck76 thanks 🙌

**Comment by cocoonkid** [comment]
Yes works. Thanks!
