### ISSUE TITLE
Release v2.0  (GigaChad)

### ISSUE THREAD

**Issue by G-Rowell** [NvChad/NvChad#310]
Dear all,

with the release of v1.0 we've made many things we're proud of, and many things that should be cleaned.
(some of the code I made definitely needs to be improved :rofl: )

Please comment below if you know of something that we need to do!

This is a running list of items that should be revisited & cleaned.

G

---
# September clean

## bugs

- [X] can't do multiple mappings to the same thing, eg. `esc_termode = "jk" & "kj"`
- [ ] can't open a folder/directory due to disabling `netrw`
- [ ] open a LSP references window with `gr` in some source code, `<leader> + x` doesn't close that window properly
- [X] <leader>e is mapped twice by default. Once to NvimTreeFocus and once to lua vim.lsp.diagnostic.show_line_diagnostics()
   - issue #455 

## refactor
- [x] re-write statusline enable/disable autocommand, currently cannot enable the statusline on `NvimTree & terminals`
  - @Akianonymus & @G-Rowell myself may work on this
- [ ] rename terminal buffer names
- [ ] catalogue all mapping keys not defined in `chadrc / default_config`, but defined within the plugin config files, centralise to `chadrc / default`

## enhancement 

- [x] Make NvChad load even faster . [check](https://www.reddit.com/r/neovim/comments/n8a094/a_simple_trick_to_load_source_code_with_neovimvim/)
- [ ] `bufferline & term issue`, multiple term buffers expand into a long name to avoid duplicates
-- prettyfy the name in this case using `bufferline - name_formatter`
- [ ] propose using a `dev` branch, and implement `version numbers, can greatly help with debugging`
  - eg, push a set of commits from `dev` to `main`, also increase version number
  - currently have no nice way of version numbering
- [ ] CI/CD for each PR & issue
  - if has more than 6 commits in PR, link to wiki page
  - if has a `merge commit` in PR, link
  - if an issue, ask to do
 - [x] chadrc option to enable dashboard on vimenter
- [x] discuss & consider using https://github.com/jose-elias-alvarez/null-ls.nvim
- [ ] Make NvimTree refresh on focus/enter
- [x] Make a `CONTRIBUTING.md`
- [ ] Make all PRs go to `NvChad/test`, not directly to `main`
   - make a GH action to always keep `test` up-to-date with `main`?

## document
- [X] check over README 
- [X] make README features toggleable
- [x] document dependencies between plugins
  - store in the website?
- [X] make a `starting & learning vim guide` on the website
  - `:h <cmd>` `:Tutor`
  - Primegean
  - NeoVim docs 
- [X] proper debugging checks
- [X] how to install NeoVim 0.5 for Debian, Ubuntu...etc.
```
sudo add-apt-repository ppa:neovim-ppa/unstable
sudo apt-get update
sudo apt-get install neovim
```
 ```
git rev-parse --short HEAD

    git rev-list HEAD | head -1
        output of this please!

    git diff origin/HEAD > diffOut.txt
        (and upload this file ofc).

    upload of ~/.cache/nvim/packer.nvim.log
```

**Comment by naser7717** [comment]
V

**Comment by ashincoder** [comment]
Guys watch TJ's videos on async and vim.schedule. He is one of the core developers in neovim
https://www.youtube.com/watch?v=GMS0JvS7W1Y
https://www.youtube.com/watch?v=GToxQKi7LZg

**Comment by G-Rowell** [comment]
Oh damn, yeah Tjs pretty cool :grin:

**Comment by ashincoder** [comment]
Guys should we use a keymap for NvimTree with prefix.

**Comment by G-Rowell** [comment]
I'm not quite sure what you mean by that, 
but the fact that you are proposing it means it something we should at least investigate and take another looks at :)

**Comment by ashincoder** [comment]
I mean that NvimTree uses CTRL-n right. Why don't we use something with prefix <leader> like eg; <leader>e

**Comment by chakrihacker** [comment]
Provide a better way to add new plugins, The problem with the current approach is whenever you update chad, the plugins added by the user will be gone.

Add some file to `.gitignore` something like user_plugins.lua and load them in packerInit or pluginList at the end of the file

**Comment by siduck76** [comment]
> Provide a better way to add new plugins, The problem with the current approach is whenever you update chad, the plugins added by the user will be gone.
> 
> Add some file to `.gitignore` something like user_plugins.lua and load them in packerInit or pluginList at the end of the file

Agreed

**Comment by Akianonymus** [comment]
> Provide a better way to add new plugins, The problem with the current approach is whenever you update chad, the plugins added by the user will be gone.
> 
> Add some file to `.gitignore` something like user_plugins.lua and load them in packerInit or pluginList at the end of the file

Soon @chakrihacker

**Comment by Anonysus69** [comment]
Can you implement a feature called total downloads?
Like this project: https://github.com/fosskers/aura
Using this method?
It's gonna be cool
https://img.shields.io/github/downloads/fosskers/aura/total.svg

**Comment by Anonysus69** [comment]
I deleted my discord account so didn't have anywhere to post suggestions

**Comment by olealgoritme** [comment]
leader+uu for update not working with latest master, since it's missing chadrc.lua

**Comment by siduck76** [comment]
> leader+uu for update not working with latest master, since it's missing chadrc.lua

@G-Rowell is working on it! so stay tuned

**Comment by marvelman3284** [comment]
> make a contributing.md 
done #494

**Comment by siduck76** [comment]
> leader+uu for update not working with latest master, since it's missing chadrc.lua

this is fixed already.

**Comment by ashincoder** [comment]
@G-Rowell Try to keep up with the PR's and modify the task list.
Fixed issue #455

**Comment by macarthy** [comment]
> > leader+uu for update not working with latest master, since it's missing chadrc.lua
> 
> this is fixed already.



I still get : 

E5108: Error executing lua ...im/site/pack/packer/start/extensions/lua/nvchad/in
it.lua:31: ENOENT: no such file or directory: /Users/macarthy/.config/nvim/lua/c
hadrc.lua

I know that is I remove clean out packer in re-pack it will probably go away

**Comment by siduck76** [comment]
im unable to reproduce the error :/

**Comment by Pocco81** [comment]
@G-Rowell what do you thing about adding a COC (Code Of Conduct)? (just a suggestion)

**Comment by siduck** [comment]
i'll close this for now since a lots of stuffs are outdated here and i'll make an updated checklist.
