### ISSUE TITLE
Ran PackerSync and lost ability to use Telescope

### ISSUE THREAD

**Issue by hsheikhali1** [NvChad/NvChad#589]
**Describe the bug**
Recently added a new plugin and proceeded to run `PackerSync` now telescope isn't working. I removed the plugin and it's still and issue..

**To Reproduce**
1. Go to nvchad
2. Run `PackerSync`
3. Try to use Telescope

**Expected behavior**
When trying to use Telescope, it should work.. but doesn't

**Screenshots**
![Screen Shot 2021-11-04 at 11 47 30 AM](https://user-images.githubusercontent.com/14851850/140368875-a8014070-d17f-49b7-b3e1-2764f20531ae.png)

**Desktop (please complete the following information):**
 - Operating System: MacOS Monterey
 - Kitty
 - v0.5.x

**Comment by siduck** [comment]
it works fine here. but leader + shift + w gives some error. also use 5.1 nvim!

**Comment by hsheikhali1** [comment]
interesting... Not sure why I am getting this

**Comment by hsheikhali1** [comment]
So, I did an update just in case but it keeps telling me Telescope doesn't exist??

**Comment by siduck** [comment]
> So, I did an update just in case but it keeps telling me Telescope doesn't exist??

when was the last time you updated nvchad?

**Comment by siduck** [comment]
backup your config somewhere and check if a clean install helps

**Comment by peppapig450** [comment]
Mine works perfectly fine on macos

**Comment by peppapig450** [comment]
https://user-images.githubusercontent.com/55930078/140431560-61770a38-c462-46fa-8885-40c7d60e04c8.mp4

**Comment by siduck** [comment]
@peppapig450 it works here too! but leader + shift + w doesnt work , try it

**Comment by peppapig450** [comment]
I don't get an error doing this either

**Comment by siduck** [comment]
> I don't get an error doing this either

did you do packersync?

**Comment by siduck** [comment]
oh you did earlier lol

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/issues/590

**Comment by peppapig450** [comment]
Idk I can't use the terminal cuz better escape refuses to work on Mac and I can't be bothered to figure out why/fix it. I almost always have 2 open. I will try it on Ubuntu in like half an hour

**Comment by siduck** [comment]
> Idk I can't use the terminal cuz better escape refuses to work on Mac and I can't be bothered to figure out why/fix it. I almost always have 2 terminals open anyways. I will try it on Ubuntu in like half an hour

just reinstall the plugin!

**Comment by peppapig450** [comment]
I tried still doesn't work.

**Comment by peppapig450** [comment]
leader shift w gives an error too

**Comment by peppapig450** [comment]
these are the lines that errored btw
```shell
awk 'NR==86, NR==106' $(find ~/.local/share -type f -name 'terms.lua')
```
```lua
   pickers.new(opts, {
      prompt_title = "Terminal buffers",
      finder = finders.new_table {
         results = buffers,
         entry_maker = opts.entry_maker or make_entry.gen_from_buffer(opts),
      },
      previewer = previewers.buffers.new(opts),
      sorter = conf.generic_sorter(opts),
      default_selection_index = default_selection_idx,
      attach_mappings = function(prompt_bufnr)
         actions.select_default:replace(function()
            local entry = action_state.get_selected_entry()
            actions.close(prompt_bufnr)

            local buf = entry.bufnr

            local chad_term, type = pcall(function()
               return vim.api.nvim_buf_get_var(buf, "term_type")
            end)
```

**Comment by peppapig450** [comment]
Found the problem and fixed it for me https://github.com/nvim-telescope/telescope.nvim/commit/97842abb038798ee51dd1f6bceb2f928f04a4c31

**Comment by peppapig450** [comment]
I changed       
```lua
previewer = previewers.buffers.new(opts),
```
to ```lua
previewer = conf.grep_previewer(opts),
```
in ~/.local/share/nvim/site/pack/packer/start/extensions/lua/telescope/_extensions/terms.lua

**Comment by siduck** [comment]
@peppapig450 thanks! I'll make the change once I get home.

**Comment by peppapig450** [comment]
np!

**Comment by siduck** [comment]
Done https://github.com/NvChad/extensions/commit/257c63dae4a1d6bed8a6766907f12f6724fd24d0

**Comment by tydra-wang** [comment]
Ran `:PackerSync` today then `:Telescope` failed with "not an editor command".

**Comment by Ay-355** [comment]
Same thing happening with me, I tried a clean install but it didn't work.

**Comment by siduck** [comment]
Try using neovim 0.5.2 which is the latest stable release.

**Comment by GreatestOfAllTimee** [comment]
> 
> 
> Done [NvChad/extensions@257c63d](https://github.com/NvChad/extensions/commit/257c63dae4a1d6bed8a6766907f12f6724fd24d0)

Fixed! run :PackerSync and it fixed

**Comment by hsheikhali1** [comment]
Can confirm it's working for me too! Thanks for the speedy fix guys

**Comment by SleepyCatOnTheBed** [comment]
I am installing nvchad on new system and receive this error. I have tried packer sync, reinstalled many times, even i used the old config on my older system still not working.
![Screenshot from 2021-11-07 22-55-09](https://user-images.githubusercontent.com/71932200/140652365-fa9f6ac5-81ab-44fd-aee4-986b39fed26d.png)

**Comment by siduck** [comment]
> I am installing nvchad on new system and receive this error. I have tried packer sync, reinstalled many times, even i used the old config on my older system still not working. ![Screenshot from 2021-11-07 22-55-09](https://user-images.githubusercontent.com/71932200/140652365-fa9f6ac5-81ab-44fd-aee4-986b39fed26d.png)

make sure you have clang / gcc

**Comment by SleepyCatOnTheBed** [comment]
@siduck Everything works normally now, thank you for your help ! How silly of me.

**Comment by tydra-wang** [comment]
Still not work for me.

Using the latest main branch, ran `:PackerSync`, `:Telescope` got:

```
Error in packer_compiled: ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:83: Vim:E492: Not an editor command: Telescope
Please check your config for correctness
```

**Comment by siduck** [comment]
> Still not work for me.
> 
> Using the latest main branch, ran `:PackerSync` with no errors, `:Telescope` got:
> 
> ```
> Error in packer_compiled: ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:83: Vim:E492: Not an editor command: Telescope
> Please check your config for correctness
> ```

this is very weird :/ . I think the issue might be with your nvim version

**Comment by Ay-355** [comment]
Make sure your using neovim 0.5.1. Telescope requires it to work.

**Comment by tydra-wang** [comment]
> Make sure your using neovim 0.5.1. Telescope [requires](https://github.com/nvim-telescope/telescope.nvim#getting-started) it to work.

Sorry, I missed this. It works now.

**Comment by SleepyCatOnTheBed** [comment]
@siduck All features of telescope after i install gcc/clang is working perfectly; however, whenever i open nvim, telescope.fzf.nvim keep pulling updates. Does failing to install telescope.fzf.nvim cause that ?

**Comment by siduck** [comment]
> @siduck All features of telescope after i install gcc/clang is working perfectly; however, whenever i open nvim, telescope.fzf.nvim keep pulling updates. Does failing to install telescope.fzf.nvim properly cause that ?

weird , are you on windows?

**Comment by SleepyCatOnTheBed** [comment]
I am not, but i am dual booting win 10 and ubuntu

**Comment by SleepyCatOnTheBed** [comment]
I don't think this is a solution, but i try to remove the telescope native fzf, then reinstall it alone again and the issue goes away. It is very weird tbh.

**Comment by siduck** [comment]
> I don't think this is a solution, but i try to remove the telescope native fzf, then reinstall it alone again and the issue goes away. It is very weird tbh.

great! at least its fixed :laughing:
